apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: almerico/github-runner:latest
        env:
        - name: GITHUB_OWNER
          value: EEOC
        - name: GITHUB_REPOSITORY
          value: alfresco-azurerm-aks-staging-environment
        - name: RUNNER_NAME
          value: EEOC-kubernetes
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token