name: Docker
on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: github-runner
  UPDATEBOT_VERSION: 1.1.53
  JX_RELEASE_VERSION: 1.0.24
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Infrastructure
        run: |
          echo ${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN}}
          echo -e "https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN}}@github.com" >>  ~/.git-credentials
          mkdir  $HOME/tmp
          curl -Ls https://github.com/jenkins-x/jx-release-version/releases/download/v${JX_RELEASE_VERSION}/jx-release-version_${JX_RELEASE_VERSION}_linux_amd64.tar.gz|  tar xvz -C $HOME/tmp;
          curl -Ls -o $HOME/tmp/updatebot.jar   https://repo1.maven.org/maven2/io/jenkins/updatebot/updatebot/${UPDATEBOT_VERSION}/updatebot-${UPDATEBOT_VERSION}.jar
          sudo cp $HOME/tmp/jx-release-version /usr/bin/jx-release-version
          sudo cp $HOME/tmp/updatebot.jar  /usr/bin/updatebot.jar
          echo "java -jar /usr/bin/updatebot.jar \$@" > $HOME/tmp/updatebot
          sudo cp $HOME/tmp/updatebot  /usr/bin/updatebot
          sudo chmod a+x /usr/bin/updatebot
          jx-release-version > VERSION;
      - name: Push image to GitHub Container Registry
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_SERVER }} --username ${{ secrets.REGISTRY_USER }} --password-stdin
          docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_SERVER }}/alfresco/$IMAGE_NAME:$(cat VERSION)
          docker images
          docker push ${{ secrets.REGISTRY_SERVER }}/alfresco/$IMAGE_NAME:$(cat VERSION)
          docker tag ${{ secrets.REGISTRY_SERVER }}/alfresco/$IMAGE_NAME:$(cat VERSION) ${{ secrets.REGISTRY_SERVER }}/alfresco/$IMAGE_NAME:latest
          docker push ${{ secrets.REGISTRY_SERVER }}/alfresco/$IMAGE_NAME:latest
      - name: Tag
        run: |
         ls -la 
         echo " version is $(cat VERSION)"
         git config --global user.email "eeoc@eeoc.com"
         git config --global user.name "EEOC" 
         git add --all;
         git commit -m "release $(cat VERSION)" ;
         git tag -fa v$(cat VERSION) -m "Release version $(cat VERSION)";
         git show-ref
         git push origin v$(cat VERSION);
#       - name: Updatebot
#         run: updatebot push-regex -r "\s+tag:\s(.*)" -v  "$(cat VERSION)" --previous-line "\s+repository:.*/alfresco/alfresco-content-repository-docker" **/values.yaml

  
